/**
 * Build step for Vercel.
 *
 * Your site is plain static files, and browsers can't read server environment
 * variables. So at deploy time this script:
 *   1. reads SUPABASE_URL and SUPABASE_ANON_KEY from Vercel's Environment Variables
 *   2. writes them into dist/config.js  (window.__ENV__ = {...})
 *   3. copies your static files (index.html, app.js, styles.css, images...) into dist/
 *
 * Locally: put the values in a .env file (see .env.example) and run `node build.js`.
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT = path.join(ROOT, 'dist');

// Files/folders that must NOT be published
const SKIP = new Set([
  'dist', 'node_modules', '.git', '.vercel', '.gitignore',
  'build.js', 'package.json', 'package-lock.json', 'vercel.json',
  '.env', '.env.local', '.env.example', 'README.md', 'config.js',
]);

// --- tiny .env loader for local builds (Vercel injects real env vars itself) ---
function loadDotEnv() {
  const file = path.join(ROOT, '.env');
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!m || line.trim().startsWith('#')) continue;
    const val = m[2].replace(/^['"]|['"]$/g, '');
    if (process.env[m[1]] === undefined) process.env[m[1]] = val;
  }
}
loadDotEnv();

const url = (process.env.SUPABASE_URL || '').trim();
const key = (process.env.SUPABASE_ANON_KEY || '').trim();
const onVercel = !!process.env.VERCEL;

function fail(msg) {
  console.error('\n✗ ' + msg + '\n');
  process.exit(1);
}

if (!url || !key) {
  const msg =
    'Missing SUPABASE_URL and/or SUPABASE_ANON_KEY.\n' +
    '  Vercel: Project → Settings → Environment Variables → add both, then redeploy.\n' +
    '  Local:  copy .env.example to .env and fill it in.';
  if (onVercel) fail(msg);
  console.warn('\n⚠ ' + msg + '\n  Continuing — the site will load but sign-in and leaderboard will not work.\n');
}

if (url && !/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(url)) {
  console.warn('⚠ SUPABASE_URL does not look like https://<project-ref>.supabase.co');
}

// Safety net: never ship a secret/service-role key to the browser.
function looksSecret(k) {
  if (/^sb_secret_/i.test(k)) return true;
  const parts = k.split('.');
  if (parts.length === 3) {
    try {
      const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8'));
      return payload.role === 'service_role';
    } catch (_) { /* not a JWT */ }
  }
  return false;
}
if (key && looksSecret(key)) {
  fail('SUPABASE_ANON_KEY is a SECRET / service_role key. Never put that in a browser app.\n' +
       '  Use the publishable (sb_publishable_...) or anon key instead, and rotate the leaked secret key in Supabase.');
}

// --- build ---
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

function copyDir(src, dest) {
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (src === ROOT && SKIP.has(entry.name)) continue;
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      fs.mkdirSync(to, { recursive: true });
      copyDir(from, to);
    } else {
      fs.copyFileSync(from, to);
    }
  }
}
copyDir(ROOT, OUT);

const config =
  '// Auto-generated by build.js — do not edit.\n' +
  'window.__ENV__ = Object.freeze(' +
  JSON.stringify({ SUPABASE_URL: url, SUPABASE_ANON_KEY: key }) +
  ');\n';
fs.writeFileSync(path.join(OUT, 'config.js'), config);

console.log('✓ Built to dist/  (' + fs.readdirSync(OUT).join(', ') + ')');
